export const planets = {
  mercury: {
    name: "Mercury",
    nickname: "The Swift Planet",
    description:
      "Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun's planets. Mercury is one of four terrestrial planets in the Solar System, and is a rocky body like Earth.",
    moons: "None",
    radius: "2,439.7 km or 1,516 mi",
    distanceFromSun: "57.9 million km or 35.98 million mi",
    orbitalPeriod: "88 Earth Days",
    image: "mercury.png",
    color: "#B5B5B5",
  },
  venus: {
    name: "Venus",
    nickname: "The Morning Star",
    description:
      "Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the brightest natural object in Earth's night sky after the Moon, Venus can cast shadows and can be, on rare occasion, visible to the naked eye in broad daylight.",
    moons: "None",
    radius: "6,051.8 km or 3,760 mi",
    distanceFromSun: "108.2 million km or 67.24 million mi",
    orbitalPeriod: "225 Earth Days",
    image: "venus.png",
    color: "#F97C5C",
  },
  earth: {
    name: "Earth",
    nickname: "The Blue Planet",
    description:
      "Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 29.2% of Earth's surface is land consisting of continents and islands. The remaining 70.8% is covered with water, mostly by oceans, seas, gulfs, and other salt-water bodies, but also by lakes, rivers, and other fresh water, which together constitute the hydrosphere.",
    moons: "The Moon",
    radius: "6,371 km or 3,959 mi",
    distanceFromSun: "149.6 million km or 92.96 million mi",
    orbitalPeriod: "365.25 Days",
    image: "earth.png",
    color: "#2F80ED",
  },
  mars: {
    name: "Mars",
    nickname: "The Red Planet",
    description:
      "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being larger than only Mercury. In English, Mars carries the name of the Roman god of war and is often referred to as the 'Red Planet'.",
    moons: "Phobos, Deimos",
    radius: "3,389.5 km or 2,106 mi",
    distanceFromSun: "228 million km or 142 million mi",
    orbitalPeriod: "687 Earth Days",
    image: "mars.png",
    color: "#EA2A4F",
  },
  jupiter: {
    name: "Jupiter",
    nickname: "The Giant Planet",
    description:
      "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined.",
    moons: "79",
    radius: "69,911 km or 43,441 mi",
    distanceFromSun: "778.5 million km or 484 million mi",
    orbitalPeriod: "11.86 Earth Years",
    image: "jupiter.png",
  },
  saturn: {
    name: "Saturn",
    nickname: "The Ringed Planet",
    description:
      "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine times that of Earth. It only has one-eighth the average density of Earth.",
    moons: "82",
    radius: "58,232 km or 36,184 mi",
    distanceFromSun: "1.43 billion km or 888 million mi",
    orbitalPeriod: "29.46 Earth Years",
    image: "saturn.png",
  },
  uranus: {
    name: "Uranus",
    nickname: "The Sideways Planet",
    description:
      "Uranus is the seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus according to Greek mythology, was the great-grandfather of Ares (Mars), grandfather of Zeus (Jupiter) and father of Cronus (Saturn).",
    moons: "27",
    radius: "25,362 km or 15,759 mi",
    distanceFromSun: "2.88 billion km or 1.79 billion mi",
    orbitalPeriod: "84.01 Earth Years",
    image: "uranus.png",
  },
  neptune: {
    name: "Neptune",
    nickname: "The Windy Planet",
    description:
      "Neptune is the eighth and farthest-known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet.",
    moons: "14",
    radius: "24,622 km or 15,299 mi",
    distanceFromSun: "4.5 billion km or 2.8 billion mi",
    orbitalPeriod: "164.8 Earth Years",
    image: "neptune.png",
  },
  pluto: {
    name: "Pluto",
    nickname: "The Dwarf Planet",
    description:
      "Pluto is an icy dwarf planet in the Kuiper belt, a ring of bodies beyond the orbit of Neptune. It was the first Kuiper belt object to be discovered and is the largest known plutoid. Pluto was discovered by Clyde Tombaugh in 1930 as the ninth planet from the Sun.",
    moons: "5",
    radius: "1,188.3 km or 737.6 mi",
    distanceFromSun: "5.91 billion km or 3.67 billion mi",
    orbitalPeriod: "248 Earth Years",
    image: "pluto.png",
  },
};
